### ISSUE TITLE
Pug (jade) icon

### ISSUE THREAD

**Issue by AdVg** [wyze/atom-seti-icons#19]
Hello, first of all thanks for the awesome icons, my favorite !

As you may already know, pug is replacing jade from version 2 and now have the .pug file extension.

It would be nice for consistency to have the same icon for pug (jade's currently icon <>).

**Comment by wyze** [comment]
Closed via https://github.com/wyze/atom-seti-icons/commit/d1f70abce06b5c9e78e5a35d155865936642c2d4 and published in [`v1.0.0`](https://github.com/wyze/atom-seti-icons/releases/tag/v1.0.0).

**Comment by AdVg** [comment]
Awesome ! Love it ! Thanks a lot ;)
