### ISSUE TITLE
Causes spacing issues

### ISSUE THREAD

**Issue by jcuenod** [wyze/atom-seti-icons#20]
When I enable seti-icons on the Atom-Material (with compact layout) the tree view takes far more space and icons don't appear to be well centred (which is also an issue in the tab bar).

**Comment by wyze** [comment]
The fix has been publish in [v1.0.1](https://github.com/wyze/atom-seti-icons/releases/tag/v1.0.1).

**Comment by jcuenod** [comment]
Impressive, thanks for the rapid response!
