### ISSUE TITLE
Confusing icons after 1.1.0

### ISSUE THREAD

**Issue by dimnls** [wyze/atom-seti-icons#23]
![capture - copy](https://cloud.githubusercontent.com/assets/3984914/15487631/b2df99a0-2157-11e6-9ddd-7e9a6dcd504a.PNG)

I'm not sure if this is on purpose but the new icons for .scss and TypeScript definitely look out of place.

**Comment by wyze** [comment]
What theme are you using? What is the output of 'apm ls' command?

**Comment by wyze** [comment]
Hey @dimnls, are you able to provide some more info? Also, did you try just reloading/restarting Atom to see if that fixed it as well?

**Comment by martinAnsty** [comment]
I had a similar thing after updating, just reloaded the window and it was fixed.

**Comment by dimnls** [comment]
I had restarted a few times but got no result. Eventually the icons were fixed and now show up fine. :+1:

**Comment by wyze** [comment]
Okay, good to hear. Will close this out as it is no longer an issue.
