### ISSUE TITLE
file icons

### ISSUE THREAD

**Issue by Tychus** [wyze/atom-seti-icons#28]
This is nothing serious but it's bugging me so hard. first file's icon is always hidden by the project folder bar or when the previous file is selected.
![image](https://cloud.githubusercontent.com/assets/1427215/15636642/333361e8-260f-11e6-9d01-3530937b7846.png)

**Comment by wyze** [comment]
Interesting, what theme are you using?

**Comment by SiSchae** [comment]
I have the same Problem. I'm using the Seti theme on atom 1.8.0.

**Comment by wyze** [comment]
This package shouldn't be used with the Seti theme itself. The Seti theme provides the icons and this package is the same set of icons, just extracted to be used with other themes.

That said, I could still look into compatibility with Seti theme.

@Tychus, are you using Seti theme as well or something different?

**Comment by dnuzum** [comment]
Also having this issue with Seti theme in combination with this package. Have been seeing it for about a month I believe...

**Comment by Tychus** [comment]
using seti-ui 1.3.1

**Comment by LukevdPalen** [comment]
Same over here.
