### ISSUE TITLE
Icons conflict with git-control after update

### ISSUE THREAD

**Issue by vrouet** [wyze/atom-seti-icons#29]
Hi,

Since I have updated seti-icons to 1.2.0, I'm having problems with the git-control plugin (https://github.com/jacogr/atom-git-control): some icons just disappear, some others are not the ones they were before.

Here's with seti-icons disabled:
![screenshot_20160530_130351](https://cloud.githubusercontent.com/assets/11041942/15648014/e24ea3d8-2667-11e6-9b43-be5c03fcd05f.png)

And when I enable it:
![screenshot_20160530_130431](https://cloud.githubusercontent.com/assets/11041942/15648015/e250fb06-2667-11e6-9ac5-3aa4c424abd9.png)

As you can see, the "commit" and the "checked" icons are missing, and the "reset" icon as well as files icons are replaced with weird ones.

**Comment by vrouet** [comment]
Update: I did some test with all the releases and had to roll all the way back to v0.4.5 for the conflict not to happen.
I'm wondering however if this is something I should report to seti-ui or even to git-control

**Comment by wyze** [comment]
I think if you enable Seti UI along with the plugin (and make sure to disable seti-icons), and there is a conflict with the plugin, then it should be an issue with Seti UI. Otherwise it's an issue with this package.

**Comment by vrouet** [comment]
I am not using seti-ui. I use dark-ui with seti-syntax.
I mentioned seti-ui because it seems you integrate their icons as-is, so I figured the conflict might exist with seti-ui as well.

**Comment by wyze** [comment]
I tried enabling it with Seti UI, so it seems the problem is there. I'll make an issue and likely send a PR there to fix it and then the fix will flow back into this package.

<img width="372" alt="screen shot 2016-06-02 at 6 16 25 pm" src="https://cloud.githubusercontent.com/assets/186971/15764256/108af9f2-28ef-11e6-9d34-ea002bca9ee7.png">
