### ISSUE TITLE
update stylus icon

### ISSUE THREAD

**Issue by DanielPintilei** [wyze/atom-seti-icons#31]
Something like this:
https://www.dropbox.com/s/d3bnz263dmz3xs6/stylus-logo.svg?dl=0
:+1:

**Comment by wyze** [comment]
Hi @DanielPintilei, this package just mirrors what is available in [jesseweed/seti-ui](https://github.com/jesseweed/seti-ui), so you should make your request over there. If approved/merged, then it will make it's way to this package!

**Comment by DanielPintilei** [comment]
ok sorry :D
