### ISSUE TITLE
No color setting is not working

### ISSUE THREAD

**Issue by german-rios-gonzalez** [wyze/atom-seti-icons#32]
The no color setting it's broken again

**Comment by wyze** [comment]
Shoot! I really need to test this, or make a script that will handle merging icon stuff from Seti UI. Fix will be out shortly.

**Comment by german-rios-gonzalez** [comment]
Thanks mate, I really love this package with no color

**Comment by wyze** [comment]
Just published [v1.3.1](https://github.com/wyze/atom-seti-icons/releases/tag/v1.3.1).
