### ISSUE TITLE
On windows icons are not in front of filename

### ISSUE THREAD

**Issue by dragouf** [wyze/atom-seti-icons#33]
with atom 1.8.0 and seti icons 1.3.1 I get this on windows :

![Image](http://i.imgur.com/m4jKdwq.png)

icons are not align with filename.

**Comment by wyze** [comment]
Hmm, not sure if that would be Windows specific. What theme are you using?

**Comment by dragouf** [comment]
I use `Atom Dark` theme. The one included with Atom.

**Comment by kiview** [comment]
This does indeed happen with `Atom Dark`, but not with `One Dark` (the new default theme).

**Comment by wyze** [comment]
Published a fix in a new release, [v1.3.2](https://github.com/wyze/atom-seti-icons/releases/tag/v1.3.2). Let me know if it doesn't solve this issue.

**Comment by kiview** [comment]
Great, works for me!
