### ISSUE TITLE
Two issues - with icons and uninstall

### ISSUE THREAD

**Issue by siberianbear** [wyze/atom-seti-icons#34]
Hello.

I've installed your package, but sadly it's going wrong.
First of all - on top-tabs with files, icons at left side from filename was positioned wrong (too bottom down the line of filename-text.
Second issue is uninstalling - I've tried to uninstall your package, but unsuccessfully, error-message is "Failed to delete seti-icons: Does not exist"
So I've just disabled it.

**Comment by GMAGD** [comment]
Try to disable other pakagaes that don't support it like geniues UI theme ....

**Comment by Positive07** [comment]
If you mean [Geneus](https://atom.io/themes/geneus-ui) theme, then pull-request #37 should fix the issue when merged in.

Overrides for other themes are needed for them to be fixed

**Comment by wyze** [comment]
Hey @siberianbear, sorry for the delayed response. Not sure why you would receive the failed to delete message.

What theme are you using where the icons aren't positioned correctly?

**Comment by siberianbear** [comment]
Hello Wyze,
Thank you for response.
Sadly I don't remember already. Too long ago.
I've solved the problem by changing the theme or something like that. Now there is no issue.

**Comment by wyze** [comment]
Okay, thank you for getting back to me!
