### ISSUE TITLE
Instructions for contributions

### ISSUE THREAD

**Issue by rtablada** [wyze/atom-seti-icons#35]
Working with some of my students, I am interested to add some different file formats to the icon set, but I'm not 100% sure where to get started.

If you could give an idea of how to modify the fonts that would be awesome.

Looking at the `project` svg, would it make sense for me to add a standalone svg.

I'm looking at making icons for `.njk` nunjucks files, `ember-cli-build.js` and `.ember-cli`.

Or if there are instructions on how to add icons within other packages that work with seti-icons would be 👍

**Comment by wyze** [comment]
Hey @rtablada, sorry for the late reply. You will need to request the icons be added in [Seti UI](https://github.com/jesseweed/seti-ui) repo first, then they will be merged into this repo. You can request new icons there by creating a new issue [here](https://github.com/jesseweed/seti-ui/issues/new).
