### ISSUE TITLE
Icons misplacement

### ISSUE THREAD

**Issue by ANyanCatFan** [wyze/atom-seti-icons#36]
For me, all icons are placed too far up when using the [Genesis UI theme](https://github.com/jmcalaway/atom-genesis-ui), like this:
<img width="110" alt="captura de pantalla 2016-08-22 a las 00 12 59" src="https://cloud.githubusercontent.com/assets/7951833/17840116/75260dbe-67fd-11e6-8b44-d5ae15dfbe08.png">
<img width="184" alt="captura de pantalla 2016-08-22 a las 00 12 07" src="https://cloud.githubusercontent.com/assets/7951833/17840145/2631055a-67fe-11e6-88c8-6ccc647790aa.png">
However, folders appear to be fine:
<img width="107" alt="captura de pantalla 2016-08-22 a las 00 16 28" src="https://cloud.githubusercontent.com/assets/7951833/17840127/b8dfc4b4-67fd-11e6-88c6-ba13df45ae0a.png">
On the default themes everything is alright.

**Comment by GMAGD** [comment]
You have to change you them to atom default them and I hope that work.

**Comment by GMAGD** [comment]
ex: One Dark

**Comment by GMAGD** [comment]
Try to disable Genesis UI theme.

**Comment by ANyanCatFan** [comment]
Yes with the default UI theme it works all well, but I want to use Genesis UI

**Comment by ANyanCatFan** [comment]
Maybe it would be better to post this issue in the Genesis UI repo

**Comment by Positive07** [comment]
Whenever #37 is merged in the [Geneus](https://atom.io/themes/geneus-ui) theme will work perfectly well with Seti-icons.

It is somewhat similar to Genesis UI, it has the "Focus mode" so it may be what you want, we have to wait for the PR to be merged in though. If you have suggestion on how the theme could be better you can always go to the [repository](https://github.com/Positive07/geneus-ui)

**Comment by wyze** [comment]
This fix is published in [v1.3.3](https://github.com/wyze/atom-seti-icons/releases/tag/v1.3.3).

**Comment by ANyanCatFan** [comment]
Thank you.
