### ISSUE TITLE
Icons for PowerShell

### ISSUE THREAD

**Issue by claudiospizzi** [wyze/atom-seti-icons#38]
Hi

Since this icon set is available in Visual Studio Code, it would be amazing if you can provide icons for PowerShell core files:
Script files: `*.ps1 `
Module definition files: `*.psd1`
Module content files: `*.psm1`

And maybe also for two special PowerShell XML file extensions:
Formatting files: `*.ps1xml`
CIM Cmdlet definitions: `*.cdxm`

**Comment by wyze** [comment]
This package for Atom is directly mirrored from [jesseweed/seti-ui](https://github.com/jesseweed/seti-ui), so in order for icons to be added here, they must be added in Seti UI first.

I see you already made your request over there, so if they get added, they will be added to this package shortly after release!
