### ISSUE TITLE
I how did that happen.

### ISSUE THREAD

**Issue by liuchangxing** [wyze/atom-seti-icons#40]
![qq 20160922231324](https://cloud.githubusercontent.com/assets/22342099/18754158/3ce88e8c-811a-11e6-8c5f-7061f225ce2b.png)
Please help me.

**Comment by wyze** [comment]
Is it still like this after you restart or reload Atom? If so, what is the output of your `apm ls` command?

**Comment by liuchangxing** [comment]
I'm sorry,I don't know why，My ICONS cannot be modified, I gave it up now

**Comment by wyze** [comment]
Since you have given up on the issue, I will close it.
