### ISSUE TITLE
Show HTML5 icon for .html.erb files

### ISSUE THREAD

**Issue by ruppalsingh** [wyze/atom-seti-icons#43]
I love the icons on this package. However, on my Rails app, all of it looks like Ruby in the filetree. Would love it if `.html.erb` were shown with the HTML5 icon (perhaps, in a red shade instead of the usual orange HTML5 -- to differentiate it as a Ruby HTML file), as most other icon-sets do -- even the most popular one `file-icons`

**Comment by wyze** [comment]
Hi @ruppalsingh, can you make the request over at https://github.com/jesseweed/seti-ui/issues/new .. Once it is merged there it will be mirrored here.

**Comment by ruppalsingh** [comment]
Thanks. I've opened this issue on the `seti-ui` package. :)
