### ISSUE TITLE
Misalignment with Spacegray UI

### ISSUE THREAD

**Issue by kadza93** [wyze/atom-seti-icons#47]
Hi,

I have been fielding for quite some time to make seti icons to work how they are supposed too i just cant find the right style to target that would fix misalignment  i will attach few photos so you can see what i am talking about.

![2016-10-29](https://cloud.githubusercontent.com/assets/9012882/19825122/cfa15a5c-9d75-11e6-94bb-53b02c597685.png)

![t1](https://cloud.githubusercontent.com/assets/9012882/19825142/01640080-9d76-11e6-8d59-62023d878eaa.png)

The tabs are kinda overlapping as you can see and the text or icon are off by few px is there a quick fix for this because i just could not find the selective style to alter and not affect whole tab area. Note that the regular file-icons work just fine.

**Comment by kadza93** [comment]
This is the quick remedy that i managed to conjure it works fine in my opinion, but it is not real solution. Copy those lines at the end of Atom > styles.less

```
atom-workspace .tab-bar .tab .title::before {
    font-size: 22px;
    line-height: 9px;
    margin-left: -26px;
    margin-top: 10px;
    position: absolute;
}

.tab-bar .tab {
    margin-left: 28px;
}

atom-workspace .tab-bar .tab .title::before {
    font-size: 22px;
    line-height: 9px;
    margin-left: -26px;
    margin-top: 10px;
    position: absolute;
}

.tab-bar .tab {
    margin-left: 28px;
}

```

**Comment by wyze** [comment]
Hi @kadza93, that fix looks acceptable to me. Would you want to send over a PR and follow what I am doing for other themes in this file: [styles/theme-overrides.less](https://github.com/wyze/atom-seti-icons/blob/master/styles/theme-overrides.less)
