### ISSUE TITLE
How can I add new ones?

### ISSUE THREAD

**Issue by KrunchMuffin** [wyze/atom-seti-icons#5]
Do I have to request or can I add them myself?

**Comment by wyze** [comment]
If you can, go ahead and just add them yourself.

**Comment by KrunchMuffin** [comment]
I would, but not sure how to.

**Comment by wyze** [comment]
I tried before, but was unsuccessful. Maybe @Arqu can explain how he was able to add them?

**Comment by Arqu** [comment]
Yeah... we'll long story short, its probably easier to regenerate the entire thing using icomoon. However that requires that you import all the icons (font) into icomoon, re-mapping them and than exporting the entire thing and then hand mapping most of the icons to values that are used within atom.

The other way is, just send me the svgs and I'll add them in the next week or so, as soon as I get some spare "hobby project time".

**Comment by popara** [comment]
Can you please add icons for Livescript? 

https://github.com/unclechu/LiveScript-logo
the extension is `.ls` 

Many thanks! :)

**Comment by Arqu** [comment]
Will do when I get some spare time :)

**Comment by wyze** [comment]
I've decided to keep this a 1:1 mirror of the icons from Seti UI. To add new icons follow the instructions over there for [Adding File Icons](https://github.com/jesseweed/seti-ui#adding-file-icons) and then I will migrate it here or accept a PR for it here. Thanks!
