### ISSUE TITLE
Icons slightly offgrid

### ISSUE THREAD

**Issue by saresq** [wyze/atom-seti-icons#55]
![image](https://cloud.githubusercontent.com/assets/14084716/23519397/82d41c72-ff55-11e6-8d0a-24698411fa41.png)
![image](https://cloud.githubusercontent.com/assets/14084716/23519420/96b4c48a-ff55-11e6-92af-86a3c5897af6.png)

![image](https://cloud.githubusercontent.com/assets/14084716/23519406/87dfad9e-ff55-11e6-8842-106544a57fa8.png)

**Comment by wyze** [comment]
I believe this is a duplicate of #54. Are you on Windows by chance?

**Comment by saresq** [comment]
Yes sorry, didnt see the issue

Thank you. My bad!
