### ISSUE TITLE
Icon Alignment

### ISSUE THREAD

**Issue by TimothyCole** [wyze/atom-seti-icons#56]
Update 1.4.1 that was supposed to "Fix alignment issues on Windows" broke alignment on Windows.
_(Was working fine before update)_

![2xfojg0k3i](https://cloud.githubusercontent.com/assets/6754577/23583626/dc8126ca-0117-11e7-9572-61b0a5069568.png)

---

Downgraded to 1.3.4 till fixed
```
apm install seti-icons@1.3.4
```

**Comment by wyze** [comment]
Which theme are you using?

**Comment by TimothyCole** [comment]
**UI Theme:** Atom Material
**Syntax Theme:** Monokai

**Comment by wyze** [comment]
This is released in [v1.4.2](https://github.com/wyze/atom-seti-icons/releases/tags/v1.4.2).
