### ISSUE TITLE
Icon size/scaling is incorrect/blurred

### ISSUE THREAD

**Issue by lech** [wyze/atom-seti-icons#57]
I'm not sure if it's just me or if I tripped a setting on accident. However it feels like some of the icon scaling since the last bug - incorrect icons and misalignment on update within issue #54, feels a bit off. I didn't notice it until I looked at my shell script icon and noticed it not having any detail as seen in this screenshot:

![scaling](https://cloud.githubusercontent.com/assets/396861/23584027/c2ac0460-011a-11e7-9ebf-8aa73d0b0d05.png)

Am I going crazy with some settings being off or is something here amiss?

**Comment by wyze** [comment]
I just looked at this, the details are there for me on macOS, but not when I tested it in Windows. This should probably be filed over on Seti UI issue tracker.

**Comment by lech** [comment]
The seti-ui project doesn't appear to have issue tracking enabled. :/

**Comment by wyze** [comment]
I see it. You should be able to create a new issue with this link: https://github.com/jesseweed/seti-ui/issues/new

**Comment by lech** [comment]
Ahh, will do! I saw that you have repo and suspected you might have been referring to that, apparently not 😏 Will report there, thanks!
