### ISSUE TITLE
Icons vertical alignment in the tabs

### ISSUE THREAD

**Issue by tuncelmert** [wyze/atom-seti-icons#58]
Vertical alignment got broken after updating to 1.4.2;

Using Atom Material theme;

![image](https://cloud.githubusercontent.com/assets/10927444/23756136/609f410e-04eb-11e7-9bbc-3672eb711f69.png)

**Comment by wyze** [comment]
Thanks! It looks like when I copied over the fix from my Windows VM, I misplaced the styles. Let's see if I can get it right this time. :)

**Comment by wyze** [comment]
This was fixed via https://github.com/wyze/atom-seti-icons/commit/cf25937c945277c8469ca1279fad4e6626469051 and published in [v1.4.3](https://github.com/wyze/atom-seti-icons/releases/tag/v1.4.3).
