### ISSUE TITLE
Tree view is a little broken

### ISSUE THREAD

**Issue by lgraziani2712** [wyze/atom-seti-icons#59]
### Description
When you try to click (left or right click) on a file or folder, it clicks the next one below him (only if there is one on the same tree level).

- Platform: windows
- Atom version: 1.16.0-beta0
- Seti-icons version: 1.4.3
- UI Theme: One Dark

By the way, when I disable seti-icons it works everything as expected.

### Mouse hovering `.dev-elements` folder with seti-icons active

![with seti icons](https://cloud.githubusercontent.com/assets/15050200/23833068/4f1d7866-071f-11e7-9278-09f479d4ca07.png)

### Mouse hovering `.dev-elements` folder with seti-icons disabled

![without seti icons](https://cloud.githubusercontent.com/assets/15050200/23833088/9492ae66-071f-11e7-897b-c2aa7e30ca31.png)

**Comment by lgraziani2712** [comment]
By the way, not always happens.

If the pointer is over the file/folder name, it will click that file/folder. If it's over the icon, it will open the one below only if that one has a custom icon.

**Comment by wyze** [comment]
I'm not sure I follow this one 100%. Does this happen on the latest stable? I noticed you are using a beta. Would this be something you could send over a PR for?

**Comment by lgraziani2712** [comment]
Sorry, but I never did anything on atom. I don't know where to start debugging things to *at least* write a test about it.

BTW, today I tried it on Atom 1.15.0 (latest release) and the bug is still there.

**Comment by wyze** [comment]
Please check the latest version of both Atom (1.17.0) and Seti Icons (1.5.0) and let me know if the issue persists.

**Comment by lgraziani2712** [comment]
I can confirm is fixed.

Now the icons are wrong placed :P

![image](https://cloud.githubusercontent.com/assets/15050200/26206591/a494839a-3bbb-11e7-9adb-66ad3c39411e.png)

I'm using Atom 1.18.0-beta0 (I know, it is a beta, but is good to know right?).

Thank you @wyze.

**Comment by wyze** [comment]
Still the same theme? I am thinking it is Windows being weird, because it looks fine for me.

**Comment by lgraziani2712** [comment]
Yep, same theme

**Comment by brock-martin** [comment]
Just updated to 1.5.0 and I'm also seeing icons off in the tree view: 

![tree icons](https://cloud.githubusercontent.com/assets/20828425/26210981/4bfba278-3bbf-11e7-9db6-eb64ff40bba5.PNG)

I'm using Windows 10, Atom 1.17.0 x64, One Dark theme

**Comment by saresq** [comment]
+1, this is happening to me too :/
![image](https://cloud.githubusercontent.com/assets/14084716/26262782/52ba8622-3cac-11e7-9063-3c4272d8f6dd.png)
