### ISSUE TITLE
Why the icons are shown as rectangle ?

### ISSUE THREAD

**Issue by Sakuyakun** [wyze/atom-seti-icons#61]
Platform: macos
Atom version: 1.15.0 x64
Seti-icons version: 1.4.3
UI Theme: One Dark

![image](https://cloud.githubusercontent.com/assets/16361069/24687412/167955a4-19ec-11e7-8cfc-c1e9a5cae8a9.png)

**Comment by wyze** [comment]
Seems like a font issue. Have you tried reloading Atom or disable/enable the plugin?

**Comment by Sakuyakun** [comment]
I have tried but it didn't work

**Comment by wyze** [comment]
Please check the latest version (1.5.0) and see if that changes anything. If not, can you see if the same thing happens when you use Seti UI?
