### ISSUE TITLE
Vertical Alignment in Tab

### ISSUE THREAD

**Issue by KTsarlz** [wyze/atom-seti-icons#62]
The issue on vertical alignment is still persistent..

![screenshot_78](https://cloud.githubusercontent.com/assets/9140507/24875102/80aefc50-1e59-11e7-8f97-f102684847ff.png)

**Comment by wyze** [comment]
Please check the latest version (1.5.0) and see if this is fixed for you. If not, comment back with theme name and operating system, and I will reopen.
