### ISSUE TITLE
Too big top padding with 'native-ui' theme

### ISSUE THREAD

**Issue by alexcre8or** [wyze/atom-seti-icons#63]
Too big top padding with 'native-ui' and 'Spacegray Light Neue UI'

<img width="469" alt="screen shot 2017-05-06 at 3 59 46 pm" src="https://cloud.githubusercontent.com/assets/7511671/25772499/1cbcdd72-3275-11e7-99b5-fcbf3adf4600.png">

**Comment by wyze** [comment]
I can take a look at this, or happy to accept a PR with a fix!

**Comment by wyze** [comment]
Fixed in [v1.5.0](https://github.com/wyze/atom-seti-icons/releases/tag/v1.5.0).
