### ISSUE TITLE
Add Icon for VueJS please!

### ISSUE THREAD

**Issue by himynameisdave** [wyze/atom-seti-icons#64]
Where is the icons for VueJS that were added here? https://github.com/jesseweed/seti-ui/issues/316

Thanks!

**Comment by wyze** [comment]
I can do a refresh of icons. Looks like there was just a new release of Seti UI yesterday, so the timing is good.

**Comment by wyze** [comment]
Fixed in [v1.5.0](https://github.com/wyze/atom-seti-icons/releases/tag/v1.5.0).
