### ISSUE TITLE
Tab icon off the tab box

### ISSUE THREAD

**Issue by valecarlos** [wyze/atom-seti-icons#67]
I have noticed with the latest version that when the file name on a tab is rather long, the icon will get out of the tab box and into the tab on its left:
![image](https://cloud.githubusercontent.com/assets/16101841/26456000/744b0a6c-4131-11e7-86ba-64432142044e.png)
on hover:
![image](https://cloud.githubusercontent.com/assets/16101841/26456019/88acc95a-4131-11e7-9075-bd41bb99d3ba.png)

**Comment by wyze** [comment]
Which theme are you using?

**Comment by valecarlos** [comment]
One Dark for both UI and syntax, Atom version 1.17.0 x64

**Comment by wyze** [comment]
Please try out [v1.5.2](https://github.com/wyze/atom-seti-icons/releases/tag/v1.5.2) and let me know if there is still issues.

**Comment by valecarlos** [comment]
The official current version is 1.17.0, are you suggesting to make an update to the beta?
![image](https://cloud.githubusercontent.com/assets/16101841/26680439/134a2c52-469f-11e7-8dd4-e66ba1d6166f.png)

**Comment by wyze** [comment]
No, I mean try out the latest version of this package that I released yesterday, and see if there is still an issue with the icons.
