### ISSUE TITLE
Icons are misaligned with text

### ISSUE THREAD

**Issue by aaronburrows** [wyze/atom-seti-icons#68]
In the tree view, icons are slightly above the text, and in the tabs, icons are slightly below.

Windows 10.

![image](https://cloud.githubusercontent.com/assets/884235/26462031/cb4e8dc6-4144-11e7-9f87-0a5bc123b202.png)

**Comment by vritant24** [comment]
Is the same in mac for the file tree. The tabs are very slightly above though.
![screen shot 2017-05-27 at 5 49 51 pm](https://cloud.githubusercontent.com/assets/13074644/26521389/fd792ca4-4304-11e7-9b54-2fecbfda009c.png)

**Comment by wyze** [comment]
Which theme is this using? And what version of Atom?

**Comment by wyze** [comment]
Please try out [v1.5.2](https://github.com/wyze/atom-seti-icons/releases/tag/v1.5.2) and let me know if there is still issues.
