### ISSUE TITLE
Icon in tabs overlap with close button

### ISSUE THREAD

**Issue by vritant24** [wyze/atom-seti-icons#69]
I am using the Nuclide package and the Nucleus Dark theme. The icons overlap the close button as well as the unsaved-circle. 
![screen shot 2017-05-27 at 5 51 56 pm](https://cloud.githubusercontent.com/assets/13074644/26521442/16e0effa-4306-11e7-8ac5-16577391beb4.png)

**Comment by wyze** [comment]
I will take a look at this. What version of Atom are you using?

**Comment by wyze** [comment]
Please try out [v1.5.2](https://github.com/wyze/atom-seti-icons/releases/tag/v1.5.2) and let me know if there is still issues.

**Comment by vritant24** [comment]
I'm using atom 1.17.0
The overlap has gone with the update, but the icons have moved up
![screen shot 2017-06-01 at 1 43 32 pm](https://cloud.githubusercontent.com/assets/13074644/26671845/9706e9b0-46d4-11e7-9fb7-6fdd0a5c8aed.png)

**Comment by wyze** [comment]
My mistake, I didn't check the theme you were using.

**Comment by wyze** [comment]
Should be good in v1.5.3! :)

**Comment by vritant24** [comment]
It's perfect now
